name: Deploy AWS Lambda Function

on:
  push:
    branches: [ main ]

env:
  CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    
jobs:
  change-connection-string:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        working-directory: AusyTooling-API/AusyTooling.API
        run: jq '.ConnectionStrings.DefaultConnection = env.CONNECTION_STRING' appsettings.json > "tmp" && mv "tmp" appsettings.json

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Test2
        run: cat AusyTooling-API/AusyTooling.API/appsettings.json
        
