name: Deploy AWS Lambda Function

on:
  push:
    branches: [ main ]
    
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: ls

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{env.DOTNET_ROOT}}/AusyTooling-API/AusyTooling.API/appsettings.json'
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.CONNECTION_STRING }}
          run: echo '${{env.DOTNET_ROOT}}/AusyTooling-API/AusyTooling.API/appsettings.json'
